update code

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -359,16 +359,18 @@ jobs:
                       --stack-status-filter CREATE_COMPLETE --no-paginate --output text)) 
             echo Stack names: "${STACKS[@]}"
 
-            if [[ "${CIRCLE_WORKFLOW_ID:0:7}" != "${OldWorkflowID}" ]]
-            then
-                echo "Deleting"
-                aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive 
-                aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
-                aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
-                echo 'Clean up done'  
-            else
-              echo 'Clean up failed'
-            fi
+            for fn in "${STACKS[@]}"; do
+        
+                if [[ "${CIRCLE_WORKFLOW_ID:0:7}" != "$fn" ]]; then
+                    echo "Deleting"
+                    aws s3 rm "s3://udapeople-${fn}" --recursive || { echo "Failed to delete S3 bucket"; exit 1; }
+                    aws cloudformation delete-stack --stack-name "udapeople-backend-${fn}" || { echo "Failed to delete backend stack"; exit 1; }
+                    aws cloudformation delete-stack --stack-name "udapeople-frontend-${fn}" || { echo "Failed to delete frontend stack"; exit 1; }
+                    echo "Clean up done"
+                else
+                    echo "Clean up failed"
+                fi
+            done
          
 
 workflows:
